/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package antrian;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.koneksi;

/**
 *
 * @author Qkoh St
 */
public class registrasi extends javax.swing.JFrame {
Connection cn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form registrasi
     */
    public registrasi() {
        initComponents();
        //menampilkan tanggal dan jam
        this.setLocationRelativeTo(null);
        
        new Thread(){
            public void run(){
                while (true){
                    Calendar kal= new GregorianCalendar();
                    int tahun= kal.get(Calendar.YEAR);
                    int bulan= kal.get(Calendar.MONTH)+1;
                    int hari= kal.get(Calendar.DAY_OF_MONTH);
                    int jam= kal.get(Calendar.HOUR_OF_DAY);
                    int menit= kal.get(Calendar.MINUTE);
                    int detik= kal.get(Calendar.SECOND);
                    String tanggal= +tahun+"-"+bulan+"-"+hari;
                    String waktu= +jam+":"+menit+":"+detik;
                    jLabeltanggal.setText(tanggal);
                    jLabelwaktu.setText(waktu);
                    jTextField_id.setEditable(false);
                    jTextField_noAntri.setEditable(false);
                    jTextField_sisa.setEditable(false);
                    
                    }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabeltanggal = new javax.swing.JLabel();
        jLabelwaktu = new javax.swing.JLabel();
        jLabeltanggal1 = new javax.swing.JLabel();
        jLabeltanggal2 = new javax.swing.JLabel();
        btn_close = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_setor = new javax.swing.JPanel();
        jLabelPerlu1 = new javax.swing.JLabel();
        btn_tarik = new javax.swing.JPanel();
        jLabelPerlu2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelLoket1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_reg = new javax.swing.JPanel();
        jLabelPerlu3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelLoket2 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_noAntri = new javax.swing.JTextField();
        jTextField_sisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_BG.setBackground(new java.awt.Color(255, 153, 51));
        jPanel_BG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        jPanel_BG.setPreferredSize(new java.awt.Dimension(1365, 735));

        jPanel_Header.setBackground(new java.awt.Color(102, 0, 204));
        jPanel_Header.setPreferredSize(new java.awt.Dimension(1365, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antrian/image/Bank_BRI_logo_Bank_Rakyat_Indonesia copy.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ANTRIAN PELAYANAN");

        jLabeltanggal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal.setText("TANGGAL");

        jLabelwaktu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelwaktu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelwaktu.setText("JAM");

        jLabeltanggal1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal1.setText("PUKUL     :");

        jLabeltanggal2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal2.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal2.setText("HARI INI : ");

        btn_close.setBackground(new java.awt.Color(204, 0, 0));
        btn_close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLOSE");

        javax.swing.GroupLayout btn_closeLayout = new javax.swing.GroupLayout(btn_close);
        btn_close.setLayout(btn_closeLayout);
        btn_closeLayout.setHorizontalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_closeLayout.setVerticalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltanggal1)
                    .addComponent(jLabeltanggal2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelwaktu)
                    .addComponent(jLabeltanggal))
                .addGap(117, 117, 117)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltanggal2)
                            .addComponent(jLabeltanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltanggal1)
                            .addComponent(jLabelwaktu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_setor.setBackground(new java.awt.Color(102, 102, 255));
        btn_setor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_setor.setPreferredSize(new java.awt.Dimension(186, 49));
        btn_setor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_setorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_setorMouseExited(evt);
            }
        });

        jLabelPerlu1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPerlu1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerlu1.setText("SETOR TUNAI");

        javax.swing.GroupLayout btn_setorLayout = new javax.swing.GroupLayout(btn_setor);
        btn_setor.setLayout(btn_setorLayout);
        btn_setorLayout.setHorizontalGroup(
            btn_setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_setorLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabelPerlu1)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        btn_setorLayout.setVerticalGroup(
            btn_setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPerlu1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        btn_tarik.setBackground(new java.awt.Color(102, 102, 255));
        btn_tarik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tarik.setPreferredSize(new java.awt.Dimension(186, 49));
        btn_tarik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tarikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tarikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tarikMouseExited(evt);
            }
        });

        jLabelPerlu2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPerlu2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerlu2.setText("TARIK TUNAI");

        javax.swing.GroupLayout btn_tarikLayout = new javax.swing.GroupLayout(btn_tarik);
        btn_tarik.setLayout(btn_tarikLayout);
        btn_tarikLayout.setHorizontalGroup(
            btn_tarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tarikLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelPerlu2)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        btn_tarikLayout.setVerticalGroup(
            btn_tarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPerlu2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOKET");

        jLabelLoket1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelLoket1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoket1.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_setor, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tarik, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLoket1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabelLoket1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(btn_setor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_tarik, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PELAYANAN LOKET");

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_reg.setBackground(new java.awt.Color(102, 102, 255));
        btn_reg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_reg.setPreferredSize(new java.awt.Dimension(186, 49));
        btn_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_regMouseExited(evt);
            }
        });

        jLabelPerlu3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPerlu3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerlu3.setText("REGISTRASI");

        javax.swing.GroupLayout btn_regLayout = new javax.swing.GroupLayout(btn_reg);
        btn_reg.setLayout(btn_regLayout);
        btn_regLayout.setHorizontalGroup(
            btn_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_regLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabelPerlu3)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        btn_regLayout.setVerticalGroup(
            btn_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPerlu3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LOKET");

        jLabelLoket2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelLoket2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoket2.setText("2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLoket2)
                        .addGap(219, 219, 219))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabelLoket2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );

        jTextField_id.setText("0");

        jTextField_noAntri.setText("0");

        jTextField_sisa.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NO ANTRIAN");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SISA ANTRIAN ");

        jLabel6.setText("0");

        jLabel7.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_noAntri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(438, 438, 438))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_noAntri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        // TODO add your handling code here:
        merah(btn_close);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        // TODO add your handling code here:
        merahTua(btn_close);
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_setorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setorMouseEntered
        // TODO add your handling code here:
        aktif(btn_setor);
    }//GEN-LAST:event_btn_setorMouseEntered

    private void btn_setorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setorMouseExited
        // TODO add your handling code here:
        backColor(btn_setor);
    }//GEN-LAST:event_btn_setorMouseExited

    private void btn_tarikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarikMouseEntered
        // TODO add your handling code here:
        aktif(btn_tarik);
    }//GEN-LAST:event_btn_tarikMouseEntered

    private void btn_tarikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarikMouseExited
        // TODO add your handling code here:
         backColor(btn_tarik);
    }//GEN-LAST:event_btn_tarikMouseExited

    private void btn_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseEntered
        // TODO add your handling code here:
        aktif(btn_reg);
    }//GEN-LAST:event_btn_regMouseEntered

    private void btn_regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseExited
        // TODO add your handling code here:
        backColor(btn_reg);
    }//GEN-LAST:event_btn_regMouseExited

    private void btn_setorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setorMouseClicked
        // TODO add your handling code here:
       
        try{
            koneksi DB = new koneksi();
                String sql = "INSERT INTO loket_1 VALUES ('"+jTextField_id.getText()+
                        "','"+jTextField_noAntri.getText()+
                        "','"+jLabelLoket1.getText()+
                        "','"+jLabelPerlu1.getText()+
                        "','"+jLabeltanggal.getText()+
                        "','"+jLabelwaktu.getText()+"')";
                java.sql.Connection conn=(Connection)koneksi.getKoneksi();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                
                ambil_id();
                ambil_no();
                ambil_sisa();
                ambil_data();
                kartu_antrian pagKart= new kartu_antrian();
                pagKart.setVisible(true);
                 }catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"PENGAMBILAN ANTRIAN GAGAL");
                System.out.println(e.getMessage());

            }
    }//GEN-LAST:event_btn_setorMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        // TODO add your handling code here:
        ambil_id();
        ambil_no();
        ambil_sisa();
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(registrasi.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void btn_tarikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarikMouseClicked
        // TODO add your handling code here:
        try{
            koneksi DB = new koneksi();
                String sql = "INSERT INTO loket_1 VALUES ('"+jTextField_id.getText()+
                        "','"+jTextField_noAntri.getText()+
                        "','"+jLabelLoket1.getText()+
                        "','"+jLabelPerlu2.getText()+
                        "','"+jLabeltanggal.getText()+
                        "','"+jLabelwaktu.getText()+"')";
                java.sql.Connection conn=(Connection)koneksi.getKoneksi();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                

                ambil_id();
                ambil_no();
                ambil_sisa();
                ambil_data();
                kartu_antrian pagKart= new kartu_antrian();
                pagKart.setVisible(true);
                 }catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"PENGAMBILAN ANTRIAN GAGAL");
                System.out.println(e.getMessage());

            }
    }//GEN-LAST:event_btn_tarikMouseClicked

    private void btn_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseClicked
        // TODO add your handling code here:
        
        try{
            koneksi DB = new koneksi();
                String sql = "INSERT INTO loket_1 VALUES ('"+jTextField_id.getText()+
                        "','"+jTextField_noAntri.getText()+
                        "','"+jLabelLoket2.getText()+
                        "','"+jLabelPerlu3.getText()+
                        "','"+jLabeltanggal.getText()+
                        "','"+jLabelwaktu.getText()+"')";
                java.sql.Connection conn=(Connection)koneksi.getKoneksi();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                
                
                ambil_id();
                ambil_no();
                ambil_sisa();
                ambil_data();
                kartu_antrian pagKart= new kartu_antrian();
                pagKart.setVisible(true);
                 }catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"PENGAMBILAN ANTRIAN GAGAL");
                System.out.println(e.getMessage());

            }
    }//GEN-LAST:event_btn_regMouseClicked
//Setting Background Tombol Navigasi
    void aktif(JPanel panel){
        panel.setBackground(new Color(51,255,255));
    }
    
    
    void backColor(JPanel panel){
        panel.setBackground(new Color(102,102,255));
    }
     void merah (JPanel panel){
        panel.setBackground(new Color(255,102,102));
    }
      void merahTua (JPanel panel){
        panel.setBackground(new Color(204,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_reg;
    private javax.swing.JPanel btn_setor;
    private javax.swing.JPanel btn_tarik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLoket1;
    private javax.swing.JLabel jLabelLoket2;
    private javax.swing.JLabel jLabelPerlu1;
    private javax.swing.JLabel jLabelPerlu2;
    private javax.swing.JLabel jLabelPerlu3;
    private javax.swing.JLabel jLabeltanggal;
    private javax.swing.JLabel jLabeltanggal1;
    private javax.swing.JLabel jLabeltanggal2;
    private javax.swing.JLabel jLabelwaktu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_noAntri;
    private javax.swing.JTextField jTextField_sisa;
    // End of variables declaration//GEN-END:variables
public void ambil_id() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MAX(Id) AS max_id FROM loket_1");
                if(rs.next())
             {
                 int id=rs.getInt("max_id");
                 int no_id=id+1;
                 String id2=Integer.toString(no_id);
                 
                 jTextField_id.setText(id2);
               
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor ID Gagal ");
         }
}

public void ambil_no() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MAX(no_antri) AS max_no FROM loket_1");
                if(rs.next())
             {
                 int no=rs.getInt("max_no");
                 int no_antrian=no+1;
                 String antri=Integer.toString(no_antrian);
                 String antri1=Integer.toString(no);
                 jTextField_noAntri.setText(antri);
                 jLabel7.setText(antri1);
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor Antrian Gagal ");
         }
}

public void ambil_sisa() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT COUNT(Id) AS sisa FROM loket_1");
                if(rs.next())
             {
                 int sisa=rs.getInt("sisa");
                 int sisa1=sisa-1;
                 String sisaAwal=Integer.toString(sisa1);
                   jLabel6.setText(sisaAwal);
                 this.jTextField_sisa.setText(rs.getString("sisa"));
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Sisa Antrian Gagal ");
         }
}

public void ambil_data() throws SQLException {
    
    kartu_antrian.no_antri = jLabel7.getText();
    kartu_antrian.sisa_antri = jLabel6.getText();
    kartu_antrian.tanggal = jLabeltanggal.getText();
    kartu_antrian.waktu = jLabelwaktu.getText();
    
}

}
