/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package antrian;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Qkoh St
 */
public class taller extends javax.swing.JFrame {
DefaultTableModel model;

 Connection cn;
    Statement st;
    ResultSet rs;
koneksi DB = new koneksi();
    /**
     * Creates new form taller
     */

    public taller() {
        initComponents();
        this.setLocationRelativeTo(null);
    try {
        tampil1();
        tampil2();
        ambil_id1();
        ambil_id2();
        ambil_dataDisplay();
    } catch (SQLException ex) {
        Logger.getLogger(taller.class.getName()).log(Level.SEVERE, null, ex);
    }
    
        new Thread(){
            public void run(){
                while (true){
                    Calendar kal= new GregorianCalendar();
                    int tahun= kal.get(Calendar.YEAR);
                    int bulan= kal.get(Calendar.MONTH)+1;
                    int hari= kal.get(Calendar.DAY_OF_MONTH);
                    int jam= kal.get(Calendar.HOUR_OF_DAY);
                    int menit= kal.get(Calendar.MINUTE);
                    int detik= kal.get(Calendar.SECOND);
                    String tanggal= +hari+"/"+bulan+"/"+tahun;
                    String waktu= +jam+" : "+menit+" : "+detik;
                    String men=Integer.toString(detik);
                            me.setText(men);
                            me.setVisible(false);
                    jLabeltanggal.setText(tanggal);
                    jLabelwaktu.setText(waktu);
                    jTextField_Layanan1.setEditable(false);
                    jTextField_Next1.setEditable(false);
                    
                    
                    }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabeltanggal = new javax.swing.JLabel();
        jLabelwaktu = new javax.swing.JLabel();
        jLabeltanggal1 = new javax.swing.JLabel();
        jLabeltanggal2 = new javax.swing.JLabel();
        btn_close = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelLoket1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_loket1 = new javax.swing.JTable();
        btn_call1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_skip1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Next1 = new javax.swing.JTextField();
        btn_CLOSELK1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_skip7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_call4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Layanan1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelLoket2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_loket2 = new javax.swing.JTable();
        btn_call2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_skip2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Next2 = new javax.swing.JTextField();
        btn_skip6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btn_CLOSELK2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btn_call3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Layanan2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        me = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_BG.setBackground(new java.awt.Color(255, 153, 51));
        jPanel_BG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        jPanel_BG.setPreferredSize(new java.awt.Dimension(1365, 735));

        jPanel_Header.setBackground(new java.awt.Color(102, 0, 204));
        jPanel_Header.setPreferredSize(new java.awt.Dimension(1365, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antrian/image/Bank_BRI_logo_Bank_Rakyat_Indonesia copy.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ANTRIAN PELAYANAN");

        jLabeltanggal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal.setText("TANGGAL");

        jLabelwaktu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelwaktu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelwaktu.setText("JAM");

        jLabeltanggal1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal1.setText("PUKUL     :");

        jLabeltanggal2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltanggal2.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltanggal2.setText("HARI INI : ");

        btn_close.setBackground(new java.awt.Color(204, 0, 0));
        btn_close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLOSE");

        javax.swing.GroupLayout btn_closeLayout = new javax.swing.GroupLayout(btn_close);
        btn_close.setLayout(btn_closeLayout);
        btn_closeLayout.setHorizontalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_closeLayout.setVerticalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltanggal1)
                    .addComponent(jLabeltanggal2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelwaktu)
                    .addComponent(jLabeltanggal))
                .addGap(117, 117, 117)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltanggal2)
                            .addComponent(jLabeltanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltanggal1)
                            .addComponent(jLabelwaktu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOKET");

        jLabelLoket1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelLoket1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoket1.setText("1");

        jTable_loket1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_loket1);

        btn_call1.setBackground(new java.awt.Color(102, 102, 255));
        btn_call1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_call1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_call1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_call1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_call1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CALL");

        javax.swing.GroupLayout btn_call1Layout = new javax.swing.GroupLayout(btn_call1);
        btn_call1.setLayout(btn_call1Layout);
        btn_call1Layout.setHorizontalGroup(
            btn_call1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_call1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btn_call1Layout.setVerticalGroup(
            btn_call1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_skip1.setBackground(new java.awt.Color(102, 102, 255));
        btn_skip1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_skip1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skip1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_skip1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_skip1MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SKIP");

        javax.swing.GroupLayout btn_skip1Layout = new javax.swing.GroupLayout(btn_skip1);
        btn_skip1.setLayout(btn_skip1Layout);
        btn_skip1Layout.setHorizontalGroup(
            btn_skip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_skip1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btn_skip1Layout.setVerticalGroup(
            btn_skip1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTextField_Next1.setText("0");

        btn_CLOSELK1.setBackground(new java.awt.Color(102, 102, 255));
        btn_CLOSELK1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CLOSELK1.setPreferredSize(new java.awt.Dimension(154, 26));
        btn_CLOSELK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CLOSELK1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CLOSELK1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CLOSELK1MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CLOSE LOKET 1");

        javax.swing.GroupLayout btn_CLOSELK1Layout = new javax.swing.GroupLayout(btn_CLOSELK1);
        btn_CLOSELK1.setLayout(btn_CLOSELK1Layout);
        btn_CLOSELK1Layout.setHorizontalGroup(
            btn_CLOSELK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CLOSELK1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_CLOSELK1Layout.setVerticalGroup(
            btn_CLOSELK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13)
        );

        btn_skip7.setBackground(new java.awt.Color(102, 102, 255));
        btn_skip7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_skip7.setPreferredSize(new java.awt.Dimension(154, 26));
        btn_skip7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skip7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_skip7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_skip7MouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("OPEN LOKET 1");

        javax.swing.GroupLayout btn_skip7Layout = new javax.swing.GroupLayout(btn_skip7);
        btn_skip7.setLayout(btn_skip7Layout);
        btn_skip7Layout.setHorizontalGroup(
            btn_skip7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_skip7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btn_skip7Layout.setVerticalGroup(
            btn_skip7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18)
        );

        btn_call4.setBackground(new java.awt.Color(102, 102, 255));
        btn_call4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_call4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_call4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_call4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_call4MouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("RISET DB");

        javax.swing.GroupLayout btn_call4Layout = new javax.swing.GroupLayout(btn_call4);
        btn_call4.setLayout(btn_call4Layout);
        btn_call4Layout.setHorizontalGroup(
            btn_call4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_call4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel22)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btn_call4Layout.setVerticalGroup(
            btn_call4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_call4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLoket1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Next1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_call1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_skip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_skip7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CLOSELK1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_Next1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_call4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLoket1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btn_skip7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CLOSELK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_skip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_call1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PELAYANAN");

        jTextField_Layanan1.setText("X");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NO ANTRIAN");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SEDANG DILAYANI DI LOKET 1 ");

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOKET");

        jLabelLoket2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelLoket2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoket2.setText("2");

        jTable_loket2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMOR ANTRIAN", "KEPERLUAN", "TANGGAL", "JAM"
            }
        ));
        jScrollPane2.setViewportView(jTable_loket2);

        btn_call2.setBackground(new java.awt.Color(102, 102, 255));
        btn_call2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_call2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_call2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_call2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_call2MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CALL");

        javax.swing.GroupLayout btn_call2Layout = new javax.swing.GroupLayout(btn_call2);
        btn_call2.setLayout(btn_call2Layout);
        btn_call2Layout.setHorizontalGroup(
            btn_call2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_call2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel12)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btn_call2Layout.setVerticalGroup(
            btn_call2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_skip2.setBackground(new java.awt.Color(102, 102, 255));
        btn_skip2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_skip2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skip2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_skip2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_skip2MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SKIP");

        javax.swing.GroupLayout btn_skip2Layout = new javax.swing.GroupLayout(btn_skip2);
        btn_skip2.setLayout(btn_skip2Layout);
        btn_skip2Layout.setHorizontalGroup(
            btn_skip2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_skip2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btn_skip2Layout.setVerticalGroup(
            btn_skip2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTextField_Next2.setText("0");

        btn_skip6.setBackground(new java.awt.Color(102, 102, 255));
        btn_skip6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_skip6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skip6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_skip6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_skip6MouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("OPEN LOKET 2 ");

        javax.swing.GroupLayout btn_skip6Layout = new javax.swing.GroupLayout(btn_skip6);
        btn_skip6.setLayout(btn_skip6Layout);
        btn_skip6Layout.setHorizontalGroup(
            btn_skip6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_skip6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_skip6Layout.setVerticalGroup(
            btn_skip6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_CLOSELK2.setBackground(new java.awt.Color(102, 102, 255));
        btn_CLOSELK2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CLOSELK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CLOSELK2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CLOSELK2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CLOSELK2MouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CLOSE LOKET 2 ");

        javax.swing.GroupLayout btn_CLOSELK2Layout = new javax.swing.GroupLayout(btn_CLOSELK2);
        btn_CLOSELK2.setLayout(btn_CLOSELK2Layout);
        btn_CLOSELK2Layout.setHorizontalGroup(
            btn_CLOSELK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CLOSELK2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_CLOSELK2Layout.setVerticalGroup(
            btn_CLOSELK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_call3.setBackground(new java.awt.Color(102, 102, 255));
        btn_call3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_call3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_call3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_call3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_call3MouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("RISET DB");

        javax.swing.GroupLayout btn_call3Layout = new javax.swing.GroupLayout(btn_call3);
        btn_call3.setLayout(btn_call3Layout);
        btn_call3Layout.setHorizontalGroup(
            btn_call3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_call3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btn_call3Layout.setVerticalGroup(
            btn_call3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_call3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLoket2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Next2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_call2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btn_skip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_skip6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CLOSELK2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_Next2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_call3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLoket2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_skip6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btn_CLOSELK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_call2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_skip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NO ANTRIAN");

        jTextField_Layanan2.setText("X");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEDANG DILAYANI DI LOKET 2");

        me.setText("jLabel17");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Layanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(194, 194, 194)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Layanan2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(me)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_Layanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Layanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(me)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        // TODO add your handling code here:
        merah(btn_close);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        // TODO add your handling code here:
        merahTua(btn_close);
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_call1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call1MouseEntered
        // TODO add your handling code here:
        aktif(btn_call1);
    }//GEN-LAST:event_btn_call1MouseEntered

    private void btn_call1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call1MouseExited
        // TODO add your handling code here:
        backColor(btn_call1);
    }//GEN-LAST:event_btn_call1MouseExited

    private void btn_skip1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip1MouseEntered
        // TODO add your handling code here:
        aktif(btn_skip1);
    }//GEN-LAST:event_btn_skip1MouseEntered

    private void btn_skip1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip1MouseExited
        // TODO add your handling code here:
        backColor(btn_skip1);
    }//GEN-LAST:event_btn_skip1MouseExited

    private void btn_call2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call2MouseEntered
        // TODO add your handling code here:
        aktif(btn_call2);
    }//GEN-LAST:event_btn_call2MouseEntered

    private void btn_call2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call2MouseExited
        // TODO add your handling code here:
        backColor(btn_call2);
    }//GEN-LAST:event_btn_call2MouseExited

    private void btn_skip2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip2MouseEntered
        // TODO add your handling code here:
        aktif(btn_skip2);
    }//GEN-LAST:event_btn_skip2MouseEntered

    private void btn_skip2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip2MouseExited
        // TODO add your handling code here:
          backColor(btn_skip2);
    }//GEN-LAST:event_btn_skip2MouseExited

    private void btn_skip1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip1MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
                String sql = "delete from loket_1 where Id='"+jTextField_Next1.getText()+"'";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil1();
                ambil_id1();
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_skip1MouseClicked

    private void btn_call1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call1MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
        ambil_antrian1();
                String sql = "delete from loket_1 where Id='"+jTextField_Next1.getText()+"'";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil1();
                ambil_id1();
                ambil_dataDisplay();
                display pagdisplay= new display();
                pagdisplay.setVisible(true);
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_call1MouseClicked

    private void btn_skip2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip2MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
                String sql = "delete from loket_1 where Id='"+jTextField_Next2.getText()+"'";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil2();
                ambil_id2();
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_skip2MouseClicked

    private void btn_call2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call2MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
        ambil_antrian2();
                String sql = "delete from loket_1 where Id='"+jTextField_Next2.getText()+"'";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil2();
                ambil_id2();
                ambil_dataDisplay2();
                display pagdisplay= new display();
                pagdisplay.setVisible(true);
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_call2MouseClicked

    private void btn_CLOSELK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK1MouseClicked
        // TODO add your handling code here:
        jTextField_Layanan1.setText("X");
        btn_CLOSELK1.setVisible(false);
        btn_call1.setVisible(false);
        btn_skip1.setVisible(false);
        btn_skip7.setVisible(true);
        
        
    }//GEN-LAST:event_btn_CLOSELK1MouseClicked

    private void btn_CLOSELK1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK1MouseEntered
        // TODO add your handling code here:
        aktif(btn_CLOSELK1);
    }//GEN-LAST:event_btn_CLOSELK1MouseEntered

    private void btn_CLOSELK1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK1MouseExited
        // TODO add your handling code here:
        backColor(btn_CLOSELK1);
    }//GEN-LAST:event_btn_CLOSELK1MouseExited

    private void btn_skip6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip6MouseClicked
        // TODO add your handling code here:
        jTextField_Layanan2.setText("0");
        btn_CLOSELK2.setVisible(true);
        btn_call2.setVisible(true);
        btn_skip2.setVisible(true);
        btn_skip6.setVisible(false);
    }//GEN-LAST:event_btn_skip6MouseClicked

    private void btn_skip6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip6MouseEntered
        // TODO add your handling code here:
         aktif(btn_skip6);
    }//GEN-LAST:event_btn_skip6MouseEntered

    private void btn_skip6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip6MouseExited
        // TODO add your handling code here:
          backColor(btn_skip6);
    }//GEN-LAST:event_btn_skip6MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btn_call1.setVisible(false);
        btn_skip1.setVisible(false);
        btn_call2.setVisible(false);
        btn_skip2.setVisible(false);
        btn_CLOSELK1.setVisible(false);
        btn_CLOSELK2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btn_skip7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip7MouseClicked
        // TODO add your handling code here:
        jTextField_Layanan1.setText("0");
        btn_CLOSELK1.setVisible(true);
        btn_call1.setVisible(true);
        btn_skip1.setVisible(true);
        btn_skip7.setVisible(false);
    }//GEN-LAST:event_btn_skip7MouseClicked

    private void btn_skip7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip7MouseEntered
        // TODO add your handling code here:
        aktif(btn_skip7);
    }//GEN-LAST:event_btn_skip7MouseEntered

    private void btn_skip7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skip7MouseExited
        // TODO add your handling code here:
        backColor(btn_skip7);
    }//GEN-LAST:event_btn_skip7MouseExited

    private void btn_CLOSELK2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK2MouseClicked
        // TODO add your handling code here:
        jTextField_Layanan2.setText("X");
        btn_CLOSELK2.setVisible(false);
        btn_call2.setVisible(false);
        btn_skip2.setVisible(false);
        btn_skip6.setVisible(true);
    }//GEN-LAST:event_btn_CLOSELK2MouseClicked

    private void btn_CLOSELK2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK2MouseEntered
        // TODO add your handling code here:
          aktif(btn_CLOSELK2);
    }//GEN-LAST:event_btn_CLOSELK2MouseEntered

    private void btn_CLOSELK2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CLOSELK2MouseExited
        // TODO add your handling code here:
        backColor(btn_CLOSELK2);
    }//GEN-LAST:event_btn_CLOSELK2MouseExited

    private void btn_call3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call3MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
        ambil_antrian1();
                String sql = "delete from loket_1 where loket=2";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil2();
                ambil_id2();
                ambil_dataDisplay();
                jTextField_Layanan2.setText("X");
                
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_call3MouseClicked

    private void btn_call3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call3MouseEntered
        // TODO add your handling code here:
        aktif(btn_call3);
    }//GEN-LAST:event_btn_call3MouseEntered

    private void btn_call3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call3MouseExited
        // TODO add your handling code here:
        backColor(btn_call3);
    }//GEN-LAST:event_btn_call3MouseExited

    private void btn_call4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call4MouseClicked
        // TODO add your handling code here:
        try{
        koneksi DB = new koneksi();
        ambil_antrian1();
                String sql = "delete from loket_1 where loket=1";

                java.sql.PreparedStatement pst=cn.prepareStatement(sql);
                pst.execute();
                tampil1();
                ambil_id1();
                ambil_dataDisplay();
                jTextField_Layanan1.setText("X");
                
                 }catch (Exception ep){
                System.out.println(ep.getMessage());

            }
    }//GEN-LAST:event_btn_call4MouseClicked

    private void btn_call4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call4MouseEntered
        // TODO add your handling code here:
        aktif(btn_call4);
    }//GEN-LAST:event_btn_call4MouseEntered

    private void btn_call4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_call4MouseExited
        // TODO add your handling code here:
        backColor(btn_call4);
    }//GEN-LAST:event_btn_call4MouseExited
//Setting Background Tombol Navigasi
    void aktif(JPanel panel){
        panel.setBackground(new Color(51,255,255));
    }
    
    
    void backColor(JPanel panel){
        panel.setBackground(new Color(102,102,255));
    }
     void merah (JPanel panel){
        panel.setBackground(new Color(255,102,102));
    }
      void merahTua (JPanel panel){
        panel.setBackground(new Color(204,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taller().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_CLOSELK1;
    private javax.swing.JPanel btn_CLOSELK2;
    private javax.swing.JPanel btn_call1;
    private javax.swing.JPanel btn_call2;
    private javax.swing.JPanel btn_call3;
    private javax.swing.JPanel btn_call4;
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_skip1;
    private javax.swing.JPanel btn_skip2;
    private javax.swing.JPanel btn_skip6;
    private javax.swing.JPanel btn_skip7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLoket1;
    private javax.swing.JLabel jLabelLoket2;
    private javax.swing.JLabel jLabeltanggal;
    private javax.swing.JLabel jLabeltanggal1;
    private javax.swing.JLabel jLabeltanggal2;
    private javax.swing.JLabel jLabelwaktu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_loket1;
    private javax.swing.JTable jTable_loket2;
    private javax.swing.JTextField jTextField_Layanan1;
    private javax.swing.JTextField jTextField_Layanan2;
    private javax.swing.JTextField jTextField_Next1;
    private javax.swing.JTextField jTextField_Next2;
    private javax.swing.JLabel me;
    // End of variables declaration//GEN-END:variables
public void tampil1() throws SQLException {
    String []judul1 = {"NOMOR ANTRIAN","KEPERLUAN","TANGGAL","JAM"};
       
                    model = new DefaultTableModel(judul1, 0);
                    jTable_loket1.setModel(model);
    int row = jTable_loket1.getRowCount();
    for(int a=0;a<row;a++){
        model.removeRow(0);
    }
        cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
        rs = cn.createStatement().executeQuery("SELECT * FROM loket_1 WHERE loket=1 order by Id asc ");
              while(rs.next()){
           
            model.addRow(new Object[]{
                 rs.getString(2),rs.getString(4),rs.getString(5),rs.getString(6),
            });
        }
    }
public void tampil2() throws SQLException {
    String []judul1 = {"NOMOR ANTRIAN","KEPERLUAN","TANGGAL","JAM"};
       
                    model = new DefaultTableModel(judul1, 0);
                    jTable_loket2.setModel(model);
    int row = jTable_loket2.getRowCount();
    for(int a=0;a<row;a++){
        model.removeRow(0);
    }
        cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
        rs = cn.createStatement().executeQuery("SELECT * FROM loket_1 WHERE loket=2 order by Id asc ");
              while(rs.next()){
           
            model.addRow(new Object[]{
                 rs.getString(2),rs.getString(4),rs.getString(5),rs.getString(6),
            });
        }
    }

public void ambil_id1() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MIN(Id) AS min_id1 FROM loket_1 WHERE loket=1");
                if(rs.next())
             {
                 int id=rs.getInt("min_id1");
                 String id1=Integer.toString(id);
                 jTextField_Next1.setText(id1);
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor ID Gagal ");
         }
}

public void ambil_id2() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MIN(Id) AS min_id2 FROM loket_1 WHERE loket=2");
                if(rs.next())
             {
                 int id=rs.getInt("min_id2");
                 String id1=Integer.toString(id);
                 jTextField_Next2.setText(id1);
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor ID Gagal ");
         }
}

public void ambil_antrian1() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MIN(Id) AS min_antr1 FROM loket_1 WHERE loket=1");
                if(rs.next())
             {
                 int id=rs.getInt("min_antr1");
                 String id1=Integer.toString(id);
                 jTextField_Layanan1.setText(id1);
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor ID Gagal ");
         }
}

public void ambil_antrian2() throws SQLException {
    try{
    cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/antrian","root","");
                rs = cn.createStatement().executeQuery("SELECT MIN(Id) AS min_antr2 FROM loket_1 WHERE loket=2");
                if(rs.next())
             {
                 int id=rs.getInt("min_antr2");
                 String id1=Integer.toString(id);
                 jTextField_Layanan2.setText(id1);
                 
             }
              
               } catch(SQLException e){
             System.out.println("Pengambilan Nomor ID Gagal ");
         }
}

public void ambil_dataDisplay() throws SQLException {
    //loket1, loket2, antri, loketnew;
    
    display.loket1 = jTextField_Layanan1.getText();
    display.loket2 = jTextField_Layanan2.getText();
    display.loketnew = jLabelLoket1.getText();
    display.antri = jTextField_Layanan1.getText();
    display.men = me.getText();
    
    
}
public void ambil_dataDisplay2() throws SQLException {
    //loket1, loket2, antri, loketnew;
    
    display.loket1 = jTextField_Layanan1.getText();
    display.loket2 = jTextField_Layanan2.getText();
    display.loketnew = jLabelLoket2.getText();
    display.antri = jTextField_Layanan2.getText();
    display.men = me.getText();
    
}
}
